apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: ngaleuj/udagram-api-feed:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-secret
        ports:
          - containerPort:  8080
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
