apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: ngaleuj/udagram-api-user:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secret
        ports:
          - containerPort:  8080
      restartPolicy: Always