language: node_js
node_js: 17

services:
  - docker

install:
  - echo "Nothing to be installed"

before_script:
  - echo "No Tests for now"

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  # - docker-compose up
after_success:

  - docker tag udagram-api-user "$DOCKER_USERNAME/udagram-api-user:latest"

  - docker tag udagram-api-feed "$DOCKER_USERNAME/udagram-api-feed:latest"

  - docker tag reverseproxy "$DOCKER_USERNAME/reverseproxy:latest"

  - docker tag udagram-frontend "$DOCKER_USERNAME/udagram-frontend:local"

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  - docker push "$DOCKER_USERNAME/udagram-api-feed:latest"

 
  - docker push "$DOCKER_USERNAME/udagram-api-user:latest"

 
  - docker push "$DOCKER_USERNAME/reverseproxy:latest"

 
  - docker push "$DOCKER_USERNAME/udagram-frontend:local"