language: node_js
node_js: 17

services:
  - docker

install:
  - echo "Nothing to be installed"

before_script:
  - echo "No Tests for now"

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker-compose up
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag udagram-api-feed "$DOCKER_USERNAME/udagram-api-feed:latest"
  - docker push "$DOCKER_USERNAME/udagram-api-feed"

  - docker tag udagram-api-user "$DOCKER_USERNAME/udagram-api-user:latest"
  - docker push "$DOCKER_USERNAME/udagram-api-user"

  - docker tag udagram-reverseproxy "$DOCKER_USERNAME/udagram-reverseproxy:latest"
  - docker push "$DOCKER_USERNAME/udagram-reverseproxy"

  - docker tag udagram-frontend "$DOCKER_USERNAME/udagram-frontend:local"
  - docker push "$DOCKER_USERNAME/udagram-frontend"